name: 'Carbonoz SolarAutopilot'
version: '1.0.0'
slug: 'carbonoz_solarautopilot'
description: 'CARBONOZ SolarAutopilot for Home Assistant with live Solar dashboard and MQTT inverter control.'
url: 'https://github.com/eelitedesire/carbonoz_solarautopilot'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
ingress: true
ingress_port: 6789
panel_icon: mdi:solar-power
panel_title: Carbonoz SolarAutopilot
hassio_api: true
homeassistant_api: true
auth_api: true
host_network: true
ports:
  3001/tcp: 3001
  6789/tcp: 6789
  7100/tcp: 7100
ports_description:
  3001/tcp: Web interface
  6789/tcp: Main application
  7100/tcp: WebSocket
map:
  - share:rw
  - ssl
discovery:
  - mqtt
services:
  - mqtt:need
mqtt:
  discovery: true
  discovery_prefix: homeassistant
options:
  mqtt_host: ''
  mqtt_port: 1883
  mqtt_username: ''
  mqtt_password: ''
  battery_number: 1
  inverter_number: 1
  database_name: ''
  database_username: ''
  database_password: ''
schema:
  mqtt_host: str
  mqtt_port: 'port'
  mqtt_username: 'str?'
  mqtt_password: 'password?'
  battery_number: int(1,)
  inverter_number: int(1,)
  database_name: 'str?'
  database_username: 'str?'
  database_password: 'password?'
